### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by bestouff** [vilcans/ld45#2]
```
Error: ResourceNotFound("/ship.dat", [("/home/xav/rust/ld45/target/debug/resources", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })), ("/home/xav/.local/share/ludumdare45", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })), ("/home/xav/.config/ludumdare45", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })), ("/home/xav/rust/ld45/resources", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })), ("/home/xav/rust/ld45/gen-resources", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" }))])
```
Apparently `ship.dat` and other resource files are missing. Could you please `git add` and `commit` them ?

**Comment by vilcans** [comment]
Those assets are built by the Makefile. Use `make resources BLENDER=blender` where `blender` is the path to the Blender binary.

**Comment by vilcans** [comment]
I've pushed a fix so `make resources` should be enough as long as `blender` is in your path.

You can also run `make run` to build and run the game.

**Comment by bestouff** [comment]
Oh yes sorry, I didn't even see there was a Makefile.  
Thanks, works like charm.
